### ISSUE TITLE
Focal Length Rounding Error

### ISSUE THREAD

**Issue by Rustymage** [stevequinn/photoborder#5]
<img width="628" alt="image" src="https://github.com/user-attachments/assets/8e7f6b9f-bb39-46b0-8344-70a13740d6b6">

Will look to understand fix and complete PR.

Good opportunity for me to learn 😄

**Comment by Rustymage** [comment]
PR appears to resolve

<img width="550" alt="image" src="https://github.com/user-attachments/assets/33e6950e-d4a9-42b1-9135-0a29f5af3ca6">

**Comment by stevequinn** [comment]
Merged into main in PR #6. Nice work 👍
