### ISSUE TITLE
Software Licensing

### ISSUE THREAD

**Issue by Rustymage** [stevequinn/photoborder#7]
Is it worth considering licensing?

The software is currently unlicensed.

https://opensource.org/licenses

Some other repos I follow and their licensing

- MIT - https://github.com/ivandokov/phockup
- AGPL3 - https://github.com/damongolding/immich-kiosk?tab=AGPL-3.0-1-ov-file
- GPL3 - https://github.com/schlagmichdoch/PairDrop?tab=GPL-3.0-1-ov-file
- MIT - https://github.com/007revad/Synology_HDD_db?tab=MIT-1-ov-file
- No License - https://github.com/cglatot/pasta
- MIT - https://github.com/bruxy70/Garbage-Collection?tab=readme-ov-file

I've not read up on reasons for or against any of the license options to date but it might be worth thinkiing about. Happy to discuss as I enjoy learning and reading up on this type of topic.

?

**Comment by stevequinn** [comment]
So, I did choose The Unlicense https://github.com/stevequinn/photoborder/blob/main/LICENSE at the time I created the app as I figured it's just for fun and I like the licence's mantra. 

Saying that, now that you're contributing and the app may grow a bit, I'd be happy to switch to the MIT licence. 

If you make a PR I'll approve 👍

**Comment by Rustymage** [comment]
https://github.com/stevequinn/photoborder/pull/8

**Comment by Rustymage** [comment]
Resolved in PR above.
